version: "3.8"
services:
  fluent-server:
    image: "fluent/fluentd:edge"
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
      - "127.0.0.1:24220:24220"
      - "127.0.0.1:9880:9880"
    volumes:
      - ./configurations/fluentd/conf:/fluentd/etc
  redis-server:
    image: "redislabs/rejson:latest"
    volumes:
      - ./configurations/redis/data:/data
      - ./configurations/redis/conf:/conf
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server /conf/redis.conf --loadmodule /usr/lib/redis/modules/rejson.so
  node-server:
    build:
      context: ../webstack
      dockerfile: ../deployment/node_server/Dockerfile
    image: node-server:prod
    ports:
      - "443:443"
    depends_on:
      - "redis-server"
      - "fluent-server"
    volumes:
      - ./configurations/node/keys:/app/keys
      - ./configurations/node/sage3-prod.hjson:/app/sage3-prod.hjson
  jupyter:
    image: "jupyter/base-notebook"
    volumes:
      - ./configurations/jupyter/conf:/conf
      - ./configurations/jupyter/notebooks:/home/jovyan/notebooks
      - ./redis-client:/home/jovyan/work
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - REDIS_URL=redis-server:6379
    depends_on:
      - "redis-server"
      - "fluent-server"
    command: /conf/start.sh
