version: "3.8"
services:
  redis-server:
    image: "redis/redis-stack-server:latest"
    volumes:
      - ./configurations/redis/data:/data
      - ./configurations/redis/conf:/conf
    ports:
      - "127.0.0.1:6379:6379"
    entrypoint: redis-server
    command: /conf/redis.conf
  python:
    image: "python:3.9-bullseye"
    volumes:
      - ./configurations/python:/code
    command: sleep infinity
  jupyter:
    image: "jupyter/base-notebook"
    volumes:
      - ./configurations/jupyter/conf:/conf
      - ./configurations/jupyter/notebooks:/home/jovyan/notebooks
      - ./redis-client:/home/jovyan/work
    ports:
      - "80:8888"
    environment:
      - REDIS_URL=redis-server:6379
      - ENVIRONMENT=development
    depends_on:
      - "redis-server"
    command: /conf/start.sh
