version: "3.8"
services:
  redis-server:
    image: "redis/redis-stack-server:latest"
    volumes:
      - ./configurations/redis/data:/data
      - ./configurations/redis/conf:/conf
    ports:
      - "127.0.0.1:6379:6379"
    entrypoint: redis-server
    command: /conf/redis.conf
  fluentd-server:
    image: "fluent/fluentd:edge-debian"
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
      - "127.0.0.1:24220:24220"
      - "127.0.0.1:9880:9880"
    volumes:
      - ./configurations/fluentd/log:/fluentd/log
      - ./configurations/fluentd/conf:/fluentd/etc
  jupyter:
    image: "jupyter/datascience-notebook"
    volumes:
      - ./configurations/jupyter/conf:/conf
      - ./configurations/jupyter/notebooks:/home/jovyan/notebooks
      - ./redis-client:/home/jovyan/work
    ports:
      - "80:8888"
    environment:
      - ENVIRONMENT=development
      - TOKEN=${TOKEN}
    depends_on:
      - "redis-server"
    command: /conf/start.sh
