name: Client macos

on:
  push:
    paths:
      - 'webstack/clients/electron/**'
      - '.github/workflows/**'
    branches:
      - dev

env:
  SERVER: production

defaults:
  run:
    shell: bash
    working-directory: webstack/clients/electron

jobs:
  run:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install
        run: yarn install --frozen-lockfile --silent
        working-directory: webstack/clients/electron
      - name: Build1
        run: npx electron-packager ./ --platform=darwin --arch=x64 --icon=s3.icns --overwrite
        working-directory: webstack/clients/electron
      - name: Build2
        run: npx electron-installer-dmg SAGE3-darwin-x64/SAGE3.app SAGE3 --dmgPath=SAGE3-darwin-x64/SAGE3-darwin-x64.dmg --icon=s3.icns --background=background.png --overwrite
        working-directory: webstack/clients/electron
      - uses: actions/upload-artifact@v3
        with:
          name: SAGE3-darwin-x64.dmg
          path: webstack/clients/electron/SAGE3-darwin-x64/SAGE3-darwin-x64.dmg

