name: Docker Image CI for DEV Branch

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:dev

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Login To GitHub Container Registry
      - name: Log in to the Container GHCR registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./deployment/node_server
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}
