name: Docker Image CI for DEV Branch

on:
  push:
    branches: ["dev", "dev-github-actions-images"]
  pull_request:
    branches: ["dev", "dev-github-actions-images"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sage3/next:dev

#permissions:
#contents: read
#packages: write

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://github.com/docker/setup-qemu-action
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v2

      # Login To GitHub Container Registry
      - name: Log in to the Container GHCR registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: deployment/node_server/Dockerfile
          context: "{{defaultContext}}:."
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
